name: baygent
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pymc
  - nutpie
  - arviz
  - preliz
  - bambi
  - networkx
  - pip
  - pip:
    - arviz-stats>=1.0.0
    - arviz-plots>=1.0.0
    - causalpy>=0.8
    - dowhy>=0.14
